const de = {
  navBar: {
    xmlUpload: "XML Hochladen",
    productionProgramm: "Produktionsprogramm",
    materialPlanning: "Materialplanung",
    orderPlanning: "Beschaffungsplanung",
    productionPlanning: "Produktionsplanung",
    capacityPlanning: "Kapazitätsplanung",
    result: "Ergebnis",
  },
  navBarText: {
    xmlUploadText:
      "Bitte laden Sie die XML-Ergebniss Datei hoch, um fortzufahren.",
    productionProgrammText:
      "Bitte geben Sie die Produktionswunsch und die Vorraussage für die kommenden drei Perioden ein.",
    materialPlanningText:
      "Bitte überprüfen Sie die Materialplannung und geben gewünschte Änderungen ein.",
    orderPlanningText:
      "Bitte überprüfen Sie die Beschaffungsplanung und geben gewünschte Änderungen ein.",
    productionPlanningText:
      "Bitte überprüfen Sie die Produktionsplanung und geben gewünschte Änderungen ein.",
    capacityPlanningText:
      "Bitte überprüfen Sie die Kapazitätsplanung und geben gewünschte Änderungen ein.",
    resultText: "Ergebnisse der Simulation.",
  },
  uploadXml: {
    xmlUploadButtonText: "XML hochladen",
  },
  productionProgramm: {
    salesorder: "Auftrag",
    forcast: "Vorhersage",
    tableLabel: "Produkt \\ Periode",
    p1: "Kinderad",
    p2: "Damenrad",
    p3: "Herrenrad",
    salesWish: "Verkaufswunsch",
    productionWish: "Produktionswunsch",
    directSellTable: "Direktverkauf",
    total: "Summe",
    amount: "Betrag",
    price: "Preis",
    penalty: "Strafe",
  },
  materialPlanning: {
    columnProduct: "Produkt",
    columnSalesorder: "Auftrag",
    columnPrevWaiting: "Vorherige Warteschlange",
    columnSafetyStock: "Sicherheitsbestand",
    columnStock: "Lagerbestand",
    columnWaitingQueue: "Warteschlange",
    columnWorkInProgress: "Laufende Arbeiten",
    columnPoductionOrders: "Produktionsaufträge",
  },
  orderPlanning: {
    columnProduct: "Produkt",
    columnDeliveryTime: "Lieferzeit",
    columnDeviation: "Abweichung",
    columnQuantityP1: "Anzahl P1",
    columnQuantityP2: "Anzahl P2",
    columnQuantityP3: "Anzahl P3",
    columnDiscountQuantity: "Rabatt Menge",
    columnStock: "Lagerberbestand",
    columnDemandForPeriod0: "Bedarf für Periode x",
    columnDemandForPeriod1: "Bedarf für Periode x+1",
    columnDemandForPeriod2: "Bedarf für Periode x+2",
    columnDemandForPeriod3: "Bedarf für Periode x+3",
    columnOrderQuantity: "Bestellmenge",
    columnOrderType: "Bestelltyp",
    columnPendingOrderPeriod: "Ausstehende Bestlellung von Periode",
    columnPendingOrderAmaunt: "Ausstehende Bestellmenge",
    columnPendingOrderType: "Bestelltyp ausstehende Bestellung",
  },
  productionPlanning: {
    order: "Bestellung",
    item: "Artikel",
    amount: "Betrag",
    times: "Arbeitsplatzzeiten",
    splitOrder: "Bestellung aufteilen",
  },
  capacityPlanning: {
    columnDesignation: "Bezechnung",
    columnFinalProduct: "Finales Produkt",
    columnArticleNumber: "Artikelnummer",
    columnProductionQuantity: "Produktionsmenge",
    columnWorkstation: "Workstation",
    backWheel: "Hinterrad",
    frontWheel: "Forderrad",
    rearMudguard: "Schutzblech hinten",
    frontMudguard: "Schutzblech vorne",
    handlebar: "Lenker",
    seat: "Sattel",
    frame: "Rahmen",
    pedal: "Pedale",
    finishedFrontWheel: "Vorderrad komplett",
    frameAndWheels: "Rahmen und Räder",
    bikeWithoutPedals: "Fahrrad ohne Pedale",
    completedBike: "Fahrrad komplett",
  },
  result: {
    tabProductionProgramm: "Productionsprogramm",
    tabOrders: "Bestellungen",
    tabProduction: "Productionsplanung",
    tabWorkingTime: "Kapazitätsplanung",
  },
  productionProgrammResult: {
    article: "Artikel",
    productionQuantity: "Produktionsmenge",
    sellDirect: "Direktverkauf",
    salesQuantity: "Verkaufsmenge",
    salesPrice: "Verkaufspreis",
    penalty: "Strafe",
  },
  orderResult: {
    article: "Artikel",
    quantity: "Menge",
    modus: "Modus",
  },
  productionResult: {
    article: "Artikel",
    quantity: "Menge",
  },
  workingTimeResult: {
    station: "Station",
    overtime: "Überstunden",
    shift: "Schicht",
  },
};

export default de;
