const en = {
  navBar: {
    xmlUpload: "Upload XML",
    productionProgramm: "Production Program",
    materialPlanning: "Material Planning",
    orderPlanning: "Order Planning",
    productionPlanning: "Production Planning",
    capacityPlanning: "Capacity Planning",
    result: "Result",
  },
  navBarText: {
    xmlUploadText: "Please upload the XML result file to proceed.",
    productionProgrammText:
      "Please enter the production wish and the forecast for the coming three periods.",
    materialPlanningText:
      "Please review the material planning and enter desired changes.",
    orderPlanningText:
      "Please review the order planning and enter desired changes.",
    productionPlanningText:
      "Please review the production planning and enter desired changes.",
    capacityPlanningText:
      "Please review the capacity planning and enter desired changes.",
    resultText: "Results of the simulation.",
  },
  uploadXml: {
    xmlUploadButtonText: "upload XML",
  },
  productionProgramm: {
    salesorder: "Salesorder",
    forcast: "Forecast",
    tableLabel: "Product \\ Period",
    p1: "Children's bike",
    p2: "Ladies' bike",
    p3: "Men's bike",
    salesWish: "Sales Wish",
    productionWish: "Production Wish",
    directSellTable: "Direct Sell",
  },
  materialPlanning: {
    columnProduct: "Product",
    columnSalesorder: "Salesorder",
    columnPrevWaiting: "Previous Waitingqueue",
    columnSafetyStock: "Safety Stock",
    columnStock: "Stock",
    columnWaitingQueue: "Waitingqueue",
    columnWorkInProgress: "Work in Progress",
    columnPoductionOrders: "Production Orders",
  },
  orderPlanning: {
    columnProduct: "Product",
    columnDeliveryTime: "Delivery Time",
    columnDeviation: "Deviation",
    columnQuantityP1: "Quantity P1",
    columnQuantityP2: "Quantity P2",
    columnQuantityP3: "Quantity P3",
    columnDiscountQuantity: "Discount Quantity",
    columnStock: "Stock",
    columnDemandForPeriod0: "Demand for Period x",
    columnDemandForPeriod1: "Demand for Period x+1",
    columnDemandForPeriod2: "Demand for Period x+2",
    columnDemandForPeriod3: "Demand for Period x+3",
    columnOrderQuantity: "Order Quantity",
    columnOrderType: "Ordertype",
    columnPendingOrderPeriod: "Pending Order Period",
    columnPendingOrderAmaunt: "Pending Order Quantity",
    columnPendingOrderType: "Pending Order Ordertype",
  },
  capacityPlanning: {
    columnDesignation: "Designation",
    columnFinalProduct: "Final Product",
    columnArticleNumber: "Article Number",
    columnProductionQuantity: "Production Quantity",
    columnWorkstation: "Workstation",
    backWheel: "Backwheel",
    frontWheel: "Frontwheel",
    rearMudguard: "Rear Mudguard",
    frontMudguard: "Front Mudguard",
    handlebar: "Handlebar",
    seat: "Seat",
    frame: "Frame",
    pedal: "Pedal",
    finishedFrontWheel: "Finished Frontwheel",
    frameAndWheels: "Frame and Wheels",
    bikeWithoutPedals: "Bike without Pedals",
    completedBike: "Completed Bike",
  },
  result: {
    tabProductionProgramm: "ProductionProgramm",
    tabOrders: "Orders",
    tabProduction: "Productionplanning",
    tabWorkingTime: "Capacityplanning",
  },
  // TODO Translation for result tables
};

export default en;
