const es = {
  navBar: {
    xmlUpload: "Cargar XML",
    productionProgramm: "Programa de Producción",
    materialPlanning: "Planificación de Material",
    orderPlanning: "Planificación de Pedidos",
    productionPlanning: "Planificación de Producción",
    capacityPlanning: "Planificación de Capacidad",
    result: "Resultado",
  },
  navBarText: {
    xmlUploadText:
      "Por favor, cargue el archivo de resultados XML para continuar.",
    productionProgrammText:
      "Por favor, introduzca el deseo de producción y la previsión para los próximos tres periodos.",
    materialPlanningText:
      "Por favor, revise la planificación de materiales e introduzca los cambios deseados.",
    orderPlanningText:
      "Por favor, revise la planificación de pedidos e introduzca los cambios deseados.",
    productionPlanningText:
      "Por favor, revise la planificación de producción e introduzca los cambios deseados.",
    capacityPlanningText:
      "Por favor, revise la planificación de capacidad e introduzca los cambios deseados.",
    resultText: "Resultados de la simulación.",
  },
  uploadXml: {
    xmlUploadButtonText: "cargar XML",
  },
  productionProgramm: {
    salesorder: "Pedido",
    forcast: "Previsión",
    tableLabel: "Producto \\ Periodo",
    p1: "Bicicleta infantil",
    p2: "Bicicleta para mujeres",
    p3: "Bicicleta para hombres",
    salesWish: "Deseo de Venta",
    productionWish: "Deseo de Producción",
    directSellTable: "Venta Directa",
    total: "Suma",
    amount: "Importe",
    price: "Precio",
    penalty: "Sanción",
  },
  materialPlanning: {
    columnProduct: "Producto",
    columnSalesorder: "Pedido",
    columnPrevWaiting: "Cola de Espera Anterior",
    columnSafetyStock: "Stock de Seguridad",
    columnStock: "Inventario",
    columnWaitingQueue: "Cola de Espera",
    columnWorkInProgress: "Trabajo en Progreso",
    columnPoductionOrders: "Órdenes de Producción",
  },
  orderPlanning: {
    columnProduct: "Producto",
    columnDeliveryTime: "Tiempo de Entrega",
    columnDeviation: "Desviación",
    columnQuantityP1: "Cantidad P1",
    columnQuantityP2: "Cantidad P2",
    columnQuantityP3: "Cantidad P3",
    columnDiscountQuantity: "Cantidad con Descuento",
    columnStock: "Inventario",
    columnDemandForPeriod0: "Demanda para el Periodo x",
    columnDemandForPeriod1: "Demanda para el Periodo x+1",
    columnDemandForPeriod2: "Demanda para el Periodo x+2",
    columnDemandForPeriod3: "Demanda para el Periodo x+3",
    columnOrderQuantity: "Cantidad de Pedido",
    columnOrderType: "Tipo de Pedido",
    columnPendingOrderPeriod: "Periodo de Pedido Pendiente",
    columnPendingOrderAmaunt: "Cantidad de Pedido Pendiente",
    columnPendingOrderType: "Tipo de Pedido Pendiente",
  },
   productionPlanning: {
    order: "Pedido",
    item: "Artículo",
    amount: "Importe",
    times: "Horario de trabajo",
    splitOrder: "Orden dividida",
  },
  capacityPlanning: {
    columnDesignation: "Denominación",
    columnFinalProduct: "Producto Final",
    columnArticleNumber: "Número de Artículo",
    columnProductionQuantity: "Cantidad de Producción",
    columnWorkstation: "Estación de Trabajo",
    backWheel: "Rueda Trasera",
    frontWheel: "Rueda Delantera",
    rearMudguard: "Guardabarros Trasero",
    frontMudguard: "Guardabarros Delantero",
    handlebar: "Manillar",
    seat: "Asiento",
    frame: "Cuadro",
    pedal: "Pedal",
    finishedFrontWheel: "Rueda Delantera Terminada",
    frameAndWheels: "Cuadro y Ruedas",
    bikeWithoutPedals: "Bicicleta sin Pedales",
    completedBike: "Bicicleta Completa",
  },
  result: {
    tabProductionProgramm: "Programa de Producción",
    tabOrders: "Pedidos",
    tabProduction: "Planificación de Producción",
    tabWorkingTime: "Planificación de Capacidad",
  },
    productionProgrammResult: {
    article: "Artículo",
    productionQuantity: "Volumen de producción",
    sellDirect: "Venta directa",
    salesQuantity: "Volumen de ventas",
    salesPrice: "Precio de venta",
    penalty: "Penalti",
  },
  orderResult: {
    article: "Artículo",
    quantity: "Cantidad",
    modus: "Modo",
  },
   productionResult: {
    article: "Artículo",
    quantity: "Cantidad",
  },
  workingTimeResult: {
    station: "Estación",
    overtime: "Horas extras",
    shift: "Turno",
  },
};

export default es;
