const vi = {
  navBar: {
    xmlUpload: "Tải lên XML",
    productionProgramm: "Chương Trình Sản Xuất",
    materialPlanning: "Kế Hoạch Nguyên Liệu",
    orderPlanning: "Kế Hoạch Đặt Hàng",
    productionPlanning: "Kế Hoạch Sản Xuất",
    capacityPlanning: "Kế Hoạch Công Suất",
    result: "Kết Quả",
  },
  navBarText: {
    xmlUploadText: "Vui lòng tải lên tệp kết quả XML để tiếp tục.",
    productionProgrammText:
      "Vui lòng nhập mong muốn sản xuất và dự báo cho ba kỳ tới.",
    materialPlanningText:
      "Vui lòng xem xét kế hoạch nguyên liệu và nhập các thay đổi mong muốn.",
    orderPlanningText:
      "Vui lòng xem xét kế hoạch đặt hàng và nhập các thay đổi mong muốn.",
    productionPlanningText:
      "Vui lòng xem xét kế hoạch sản xuất và nhập các thay đổi mong muốn.",
    capacityPlanningText:
      "Vui lòng xem xét kế hoạch công suất và nhập các thay đổi mong muốn.",
    resultText: "Kết quả của mô phỏng.",
  },
  uploadXml: {
    xmlUploadButtonText: "tải lên XML",
  },
  productionProgramm: {
    salesorder: "Đơn Đặt Hàng",
    forcast: "Dự Báo",
    tableLabel: "Sản Phẩm \\ Kỳ",
    p1: "Xe đạp trẻ em",
    p2: "Xe đạp nữ",
    p3: "Xe đạp nam",
    salesWish: "Mong Muốn Bán Hàng",
    productionWish: "Mong Muốn Sản Xuất",
    directSellTable: "Bán Trực Tiếp",
    total: "Tổng",
    amount: "Số lượng",
    price: "Giá",
    penalty: "Hình phạt",
  },
  materialPlanning: {
    columnProduct: "Sản Phẩm",
    columnSalesorder: "Đơn Đặt Hàng",
    columnPrevWaiting: "Hàng Đợi Trước",
    columnSafetyStock: "Hàng Tồn Kho An Toàn",
    columnStock: "Tồn Kho",
    columnWaitingQueue: "Hàng Đợi",
    columnWorkInProgress: "Đang Sản Xuất",
    columnPoductionOrders: "Đơn Sản Xuất",
  },
  orderPlanning: {
    columnProduct: "Sản Phẩm",
    columnDeliveryTime: "Thời Gian Giao Hàng",
    columnDeviation: "Sai Lệch",
    columnQuantityP1: "Số Lượng P1",
    columnQuantityP2: "Số Lượng P2",
    columnQuantityP3: "Số Lượng P3",
    columnDiscountQuantity: "Số Lượng Chiết Khấu",
    columnStock: "Tồn Kho",
    columnDemandForPeriod0: "Nhu Cầu Kỳ x",
    columnDemandForPeriod1: "Nhu Cầu Kỳ x+1",
    columnDemandForPeriod2: "Nhu Cầu Kỳ x+2",
    columnDemandForPeriod3: "Nhu Cầu Kỳ x+3",
    columnOrderQuantity: "Số Lượng Đặt Hàng",
    columnOrderType: "Loại Đơn Hàng",
    columnPendingOrderPeriod: "Kỳ Đơn Hàng Đang Chờ",
    columnPendingOrderAmaunt: "Số Lượng Đơn Hàng Đang Chờ",
    columnPendingOrderType: "Loại Đơn Hàng Đang Chờ",
  },
    productionPlanning: {
    order: "Đơn đặt hàng",
    item: "Mặt hàng",
    amount: "Số tiền",
    times: "Thời gian làm việc",
    splitOrder: "Chia đơn đặt hàng",
  },
  capacityPlanning: {
    columnDesignation: "Tên Gọi",
    columnFinalProduct: "Sản Phẩm Cuối",
    columnArticleNumber: "Mã Sản Phẩm",
    columnProductionQuantity: "Số Lượng Sản Xuất",
    columnWorkstation: "Trạm Làm Việc",
    backWheel: "Bánh Xe Sau",
    frontWheel: "Bánh Xe Trước",
    rearMudguard: "Chắn Bùn Sau",
    frontMudguard: "Chắn Bùn Trước",
    handlebar: "Tay Lái",
    seat: "Yên Xe",
    frame: "Khung Xe",
    pedal: "Bàn Đạp",
    finishedFrontWheel: "Bánh Trước Hoàn Chỉnh",
    frameAndWheels: "Khung và Bánh Xe",
    bikeWithoutPedals: "Xe Đạp Không Bàn Đạp",
    completedBike: "Xe Đạp Hoàn Chỉnh",
  },
  result: {
    tabProductionProgramm: "Chương Trình Sản Xuất",
    tabOrders: "Đơn Hàng",
    tabProduction: "Kế Hoạch Sản Xuất",
    tabWorkingTime: "Kế Hoạch Công Suất",
  },
  productionProgrammResult: {
    article: "Mặt hàng",
    productionQuantity: "Số lượng sản xuất",
    sellDirect: "Bán hàng trực tiếp",
    salesQuantity: "Số lượng bán hàng",
    salesPrice: "Giá bán",
    penalty: "Phạt",
  },
  orderResult: {
    article: "Mặt hàng",
    quantity: "Số lượng",
    modus: "Chế độ",
  },
   productionResult: {
    article: "Mặt hàng",
    quantity: "Số lượng",
  },
  workingTimeResult: {
    station: "Trạm làm việc",
    overtime: "Làm thêm giờ",
    shift: "Ca làm việc",
  },
};

export default vi;
