const zh = {
  navBar: {
    xmlUpload: "上传 XML",
    productionProgramm: "生产计划",
    materialPlanning: "物料计划",
    orderPlanning: "订单计划",
    productionPlanning: "生产规划",
    capacityPlanning: "产能计划",
    result: "结果",
  },
  navBarText: {
    xmlUploadText: "请上传 XML 结果文件以继续。",
    productionProgrammText: "请输入生产愿望和未来三个周期的预测。",
    materialPlanningText: "请查看物料计划并输入所需更改。",
    orderPlanningText: "请查看订单计划并输入所需更改。",
    productionPlanningText: "请查看生产计划并输入所需更改。",
    capacityPlanningText: "请查看产能计划并输入所需更改。",
    resultText: "模拟结果。",
  },
  uploadXml: {
    xmlUploadButtonText: "上传 XML",
  },
  productionProgramm: {
    salesorder: "销售订单",
    forcast: "预测",
    tableLabel: "产品 \\ 周期",
    p1: "儿童自行车",
    p2: "女士自行车",
    p3: "男士自行车",
    salesWish: "销售愿望",
    productionWish: "生产愿望",
    directSellTable: "直接销售",
    total: "数额",
    amount: "金额",
    price: "价格",
    penalty: "处罚",
  },
  materialPlanning: {
    columnProduct: "产品",
    columnSalesorder: "销售订单",
    columnPrevWaiting: "前等待队列",
    columnSafetyStock: "安全库存",
    columnStock: "库存",
    columnWaitingQueue: "等待队列",
    columnWorkInProgress: "在制品",
    columnPoductionOrders: "生产订单",
  },
  orderPlanning: {
    columnProduct: "产品",
    columnDeliveryTime: "交货时间",
    columnDeviation: "偏差",
    columnQuantityP1: "数量 P1",
    columnQuantityP2: "数量 P2",
    columnQuantityP3: "数量 P3",
    columnDiscountQuantity: "折扣数量",
    columnStock: "库存",
    columnDemandForPeriod0: "第 x 期需求",
    columnDemandForPeriod1: "第 x+1 期需求",
    columnDemandForPeriod2: "第 x+2 期需求",
    columnDemandForPeriod3: "第 x+3 期需求",
    columnOrderQuantity: "订购数量",
    columnOrderType: "订单类型",
    columnPendingOrderPeriod: "待处理订单期",
    columnPendingOrderAmaunt: "待处理订单数量",
    columnPendingOrderType: "待处理订单类型",
  },
    productionPlanning: {
    order: "订单",
    item: "文章",
    amount: "金额",
    times: "工作时间",
    splitOrder: "拆分订单",
  },
  capacityPlanning: {
    columnDesignation: "名称",
    columnFinalProduct: "最终产品",
    columnArticleNumber: "产品编号",
    columnProductionQuantity: "生产数量",
    columnWorkstation: "工作站",
    backWheel: "后轮",
    frontWheel: "前轮",
    rearMudguard: "后挡泥板",
    frontMudguard: "前挡泥板",
    handlebar: "车把",
    seat: "座位",
    frame: "车架",
    pedal: "踏板",
    finishedFrontWheel: "完成的前轮",
    frameAndWheels: "车架和轮子",
    bikeWithoutPedals: "无踏板自行车",
    completedBike: "完成的自行车",
  },
  result: {
    tabProductionProgramm: "生产计划",
    tabOrders: "订单",
    tabProduction: "生产规划",
    tabWorkingTime: "产能计划",
  },
  productionProgrammResult: {
    article: "文章",
    productionQuantity: "生产量",
    sellDirect: "直接销售",
    salesQuantity: "销售量",
    salesPrice: "销售价格",
    penalty: "处罚",
  },
  orderResult: {
    article: "文章",
    quantity: "数量",
    modus: "模式",
  },
   productionResult: {
    article: "文章",
    quantity: "数量",
  },
  workingTimeResult: {
    station: "火车站",
    overtime: "加时",
    shift: "调迁",
  },
};

export default zh;
